export const Events = {
	START: 'START',
	CARD_SELECT: 'CARD_SELECT',
	CARD_TOGGLE_BASKET: 'CARD_TOGGLE_BASKET',
	BASKET_OPEN: 'BASKET_OPEN',
	BASKET_DELETE_ITEM: 'BASKET_DELETE_ITEM',
	BASKET_START_ORDER: 'BASKET_START_ORDER',
	ORDER_TOGGLE_PAYMENT_TYPE: 'ORDER_TOGGLE_PAYMENT_TYPE',
	ORDER_CHANGE_ADDRESS: 'ORDER_CHANGE_ADDRESS',
	ORDER_CHANGE_EMAIL: 'ORDER_CHANGE_EMAIL',
	ORDER_CHANGE_PHONE: 'ORDER_CHANGE_PHONE',
	ORDER_PAYMENT_SUBMIT: 'ORDER_PAYMENT_SUBMIT',
	ORDER_CONTACT_SUBMIT: 'ORDER_CONTACT_SUBMIT',
};
