export const Events = {
	START: 'START',
	CARD_SELECT: 'CARD_SELECT',
	CARD_TOGGLE_BASKET: 'CARD_TOGGLE_BASKET',
	BASKET_OPEN: 'BASKET_OPEN',
	BASKET_DELETE_ITEM: 'BASKET_DELETE_ITEM',
	BASKET_SUBMIT: 'BASKET_SUBMIT',
};
